server:
  port: 8082

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

#logging:
##  level:
##    org.springframework.web: DEBUG
#  file:
#    name: 'D:\github\Decoder-Project\course\myLog.log'


